#!/usr/bin/env python3
"""Generate the short share pages — wordlink.au/speaking, wordlink.au/clock.

GitHub Pages serves `<name>.html` at `/<name>`, so every short address is a
real file. Each one is a title, a description and a share preview, then a
redirect to the section or game it names — the same shape as the hand-written
solo.html, which is where this pattern came from.

They are generated rather than hand-kept because there are forty of them and
they differ by five strings. Edit SECTIONS and GAMES below, then re-run:

    python3 tools/build-links.py

Then commit the changed pages. Nothing runs this at deploy time — Pages
publishes the repo as it stands, so the generated files are checked in.
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = 'https://wordlink.au'
MARKER = 'generated by tools/build-links.py'

# slug, destination, title, description
# The destination is what the app already understands; the slug is only a
# prettier way to ask for it.
SECTIONS = [
    ('alphabet', 'index.html?section=alphabet', 'The Alphabet',
     'Learn the names of the 26 English letters. Tap any letter to hear it. Free practice for adult learners.'),
    ('letter-sounds', 'index.html?section=sounds', 'Letter Sounds',
     'Hear the sound each letter makes, with example words. Free phonics practice for adult learners.'),
    ('words-1', 'index.html?section=wp1', 'Words 1 — Beginner Reading',
     'Sound out short words, one letter pattern at a time. Free reading practice for adult learners.'),
    ('words-2', 'index.html?section=wp2', 'Words 2 — Longer Words',
     'Read longer words and harder letter patterns. Free reading practice for adult learners.'),
    ('sentences', 'index.html?section=sentences&level=0', 'Read Sentences — Beginner',
     'Read short everyday sentences and hear them read aloud. Free reading practice for adult learners.'),
    ('sentences-elementary', 'index.html?section=sentences&level=1', 'Read Sentences — Elementary',
     'Read longer everyday sentences and hear them read aloud. Free reading practice for adult learners.'),
    ('speaking', 'index.html?section=speaking', 'Speaking Practice',
     'Listen to a question, record yourself answering, then compare. Free speaking practice for adult learners.'),
]

# Games. The title is the game's name on its start screen; the description
# opens with the same plain-English line the card shows.
GAMES = [
    ('beginner-sound-gap', 'wp1:gap', 'Beginner Sound Gap', 'Hear the missing sound and write it.'),
    ('beginner-tap-word', 'wp1:word', 'Beginner Tap Word', 'Hear a word and tap it.'),
    ('beginner-build-word', 'wp1:build', 'Beginner Build Word', 'Build the word from its sounds.'),
    ('elementary-sound-gap', 'wp2:gap', 'Elementary Sound Gap', 'Hear the missing sound in a longer word.'),
    ('elementary-tap-word', 'wp2:word', 'Elementary Tap Word', 'Hear a longer word and tap it.'),
    ('elementary-build-word', 'wp2:build', 'Elementary Build Word', 'Build a longer word from its sounds.'),
    ('beginner-listening', 'beginner', 'Beginner Listen and Fill Gaps', 'Listen to a sentence and fill the gaps.'),
    ('elementary-listening', 'elementary', 'Elementary Listen and Fill Gaps', 'Listen to a longer sentence and fill the gaps.'),
    ('question-words', 'questionwords', 'Question Words', 'Choose the right question word.'),
    ('numbers-1-10', 'numbers', 'Numbers 1–10', 'Hear a number from 1 to 10 and write it.'),
    ('numbers-11-20', 'numbers1120', 'Numbers 11–20', 'Hear a number from 11 to 20 and write it.'),
    ('numbers-21-99', 'numbers2199', 'Numbers 21–99', 'Hear a number from 21 to 99 and write it.'),
    ('days', 'days', 'Days of the Week', 'Hear a day of the week and write it.'),
    ('months', 'months', 'Months', 'Hear a month and write it.'),
    ('weather', 'weather', 'Weather', 'Hear a weather word and write it.'),
    ('fruits', 'fruits', 'Fruits', 'Hear the fruit and write its name.'),
    ('body', 'body', 'Parts of the Body', 'Hear a part of the body and write it.'),
    ('clothes', 'clothes', 'Clothes', 'Hear the clothing word and write it.'),
    ('spelling', 'spelling', 'All Spelling', 'Spell words from every topic.'),
    ('unscramble', 'unscramble', 'Listen and Unscramble', 'Listen, then put the words in order.'),
    ('word-order', 'gramscramble', 'Grammar Unscramble', 'Put the words in the right order.'),
    ('speaking-game', 'speaking', 'Speaking Game', 'Say the answer out loud.'),
    ('translate', 'translate', 'Translate', 'Read it in your language, write it in English.'),
    ('letter-names', 'letter', 'Letter Names', 'Hear a letter name and choose the letter.'),
    ('first-sounds', 'lettersound', 'First Sounds', 'Hear the first sound of a word.'),
    ('odd-one-out', 'oddone', 'Odd One Out', 'Find the word that does not belong.'),
    ('signs', 'signs', 'Signs', 'Read the signs you see around you.'),
    ('messages', 'sms', 'Messages', 'Read a short message and answer it.'),
    ('clock', 'clock', 'Clock', 'Read the time and write it.'),
    ('shop', 'shop', 'Shop', 'Count the coins and pay the right amount.'),
    ('dice', 'target', 'Dice', 'Roll two dice and get closest to the target.'),
    ('forms', 'forms', 'Forms', 'Fill in a form with your details.'),
    ('all-games', 'all', 'All Games', 'A mix of every game.'),
]

TAIL = ' Free English practice for adult learners. No sign-up.'

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- {marker} — do not edit by hand.
     A short, shareable address: {site}/{slug} lands straight on
     {title}. The page carries its own share preview and then hands over. -->
<title>{title} | WordLink</title>
<meta name="description" content="{desc}">
<!-- Search engines should index the app, not this hop. -->
<link rel="canonical" href="{site}/{dest_url}">

<meta property="og:type" content="website">
<meta property="og:site_name" content="WordLink">
<meta property="og:locale" content="en_AU">
<meta property="og:url" content="{site}/{slug}">
<meta property="og:title" content="{title} — WordLink">
<meta property="og:description" content="{desc}">
<meta property="og:image" content="{site}/icon-512.png">
<meta name="twitter:card" content="summary">

<!-- The refresh is the fallback for a browser with JavaScript turned off; the
     script beats it to it and uses replace() so Back returns to wherever the
     link was shared, not to this staging post. Anything after the ? comes
     along, so /{slug}?q=20 still works. -->
<meta http-equiv="refresh" content="0; url={dest}">
<script>
(function(){{
  var q=location.search.replace(/^\\?/,'');
  location.replace('{dest_js}'+(q?'&'+q:''));
}})();
</script>

<link href="fonts/fonts.css" rel="stylesheet">
<meta name="theme-color" content="{theme}">
<link rel="icon" href="favicon.ico" sizes="16x16 32x32 48x48">
<link rel="icon" type="image/png" sizes="192x192" href="icon-192.png">
<link rel="apple-touch-icon" href="icon-192.png">
<style>
*{{box-sizing:border-box;margin:0;padding:0;}}
body{{font-family:'Nunito',sans-serif;background:{bg};color:{fg};min-height:100vh;
  display:flex;flex-direction:column;align-items:center;justify-content:center;gap:22px;
  padding:24px;text-align:center;}}
h1{{font-family:'Fredoka One',cursive;font-size:1.6rem;color:{accent};font-weight:400;}}
p{{color:{muted};max-width:34ch;line-height:1.5;}}
a.btn{{display:inline-flex;align-items:center;gap:8px;font-family:'Fredoka One',cursive;
  font-size:1.2rem;padding:15px 34px;border-radius:50px;background:{accent};color:#fff;
  text-decoration:none;box-shadow:0 6px 24px {shadow};}}
</style>
</head>
<body>
  <h1>{title}</h1>
  <p>{blurb}</p>
  <a class="btn" href="{dest}">▶ Open</a>
</body>
</html>
"""

# The two halves of the app have their own palettes; a stub that flashes the
# wrong one before redirecting looks like a broken page.
LIGHT = dict(theme='#4a90d9', bg='#fdf6ec', fg='#2d2a26', accent='#4a90d9',
             muted='#7a6f65', shadow='rgba(74,144,217,.4)')
DARK = dict(theme='#0d0d1a', bg='#0d0d1a', fg='#f0f0ff', accent='#e94560',
            muted='#8888aa', shadow='rgba(233,69,96,.4)')


def write(slug, dest, title, desc, blurb, palette):
    html = PAGE.format(
        marker=MARKER, site=SITE, slug=slug, title=title, desc=desc, blurb=blurb,
        dest=dest.replace('&', '&amp;'), dest_js=dest, dest_url=dest.replace('&', '&amp;'),
        **palette)
    path = os.path.join(ROOT, slug + '.html')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    return slug + '.html'


def main():
    written = []
    for slug, dest, title, desc in SECTIONS:
        written.append(write(slug, dest, title, desc, desc.split('.')[0] + '.', LIGHT))
    for slug, game, title, blurb in GAMES:
        desc = blurb + TAIL
        written.append(write(slug, 'game.html?mode=solo&game=' + game, title, desc, blurb, DARK))

    # Keep the sitemap and the service worker in step with the pages that
    # actually exist, so a new slug is never half-added.
    slugs = [s for s, *_ in SECTIONS] + [s for s, *_ in GAMES]
    update_sitemap(slugs)
    update_sw(written)
    print('wrote %d pages' % len(written))


def update_sw(files):
    """List the short pages in the service worker's OPTIONAL set.

    OPTIONAL rather than CORE: each is cached individually and a failure does
    not block install, which is the right trade for forty small redirect pages
    that only matter to a learner who opens a shared link offline.
    """
    path = os.path.join(ROOT, 'sw.js')
    with open(path, encoding='utf-8') as f:
        js = f.read()
    block = ('  // %s — the short share addresses (/clock, /speaking).\n' % MARKER
             + ''.join("  './%s',\n" % f for f in sorted(files))
             + '  // /short links\n')
    if MARKER in js:
        js = re.sub(r'  // %s[^\n]*\n(?:.*?)  // /short links\n' % re.escape(MARKER),
                    block, js, flags=re.S)
    else:
        js = js.replace('const OPTIONAL = [\n', 'const OPTIONAL = [\n' + block, 1)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(js)


def update_sitemap(slugs):
    path = os.path.join(ROOT, 'sitemap.xml')
    with open(path, encoding='utf-8') as f:
        xml = f.read()
    entries = ''.join(
        '  <url>\n'
        '    <loc>%s/%s</loc>\n'
        '    <changefreq>monthly</changefreq>\n'
        '    <priority>0.7</priority>\n'
        '  </url>\n' % (SITE, s) for s in slugs)
    block = '  <!-- %s -->\n%s  <!-- /short links -->\n' % (MARKER, entries)
    if '<!-- ' + MARKER + ' -->' in xml:
        xml = re.sub(r'  <!-- %s -->\n.*?  <!-- /short links -->\n' % re.escape(MARKER),
                     block, xml, flags=re.S)
    else:
        xml = xml.replace('</urlset>', block + '</urlset>')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(xml)


if __name__ == '__main__':
    main()
